[tool.black]
line-length = 79
skip-string-normalization = true
py38 = true
include = '\.py$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | node_modules
)/
'''

[tool.isort]
multi_line_output = 3
default_section = "THIRDPARTY"
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
